//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace neConfig.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Back BackSpace</string>\r\n  <string>Tab TAB</string>\r\n  <string>Escape Esc<" +
            "/string>\r\n  <string>Space Space</string>\r\n  <string>PageUp PageUp</string>\r\n  <s" +
            "tring>Next PageDown</string>\r\n  <string>End End</string>\r\n  <string>Home Home</s" +
            "tring>\r\n  <string>Left ←</string>\r\n  <string>Up ↑</string>\r\n  <string>Right →</s" +
            "tring>\r\n  <string>Down ↓</string>\r\n  <string>Insert Ins</string>\r\n  <string>Dele" +
            "te Delete</string>\r\n  <string>NumPad0 num0</string>\r\n  <string>NumPad1 num1</str" +
            "ing>\r\n  <string>NumPad2 num2</string>\r\n  <string>NumPad3 num3</string>\r\n  <strin" +
            "g>NumPad4 num4</string>\r\n  <string>NumPad5 num5</string>\r\n  <string>NumPad6 num6" +
            "</string>\r\n  <string>NumPad7 num7</string>\r\n  <string>NumPad8 num8</string>\r\n  <" +
            "string>NumPad9 num9</string>\r\n  <string>Multiply num*</string>\r\n  <string>Add nu" +
            "m+</string>\r\n  <string>Subtract num-</string>\r\n  <string>Divide num/</string>\r\n " +
            " <string>Decimal num.</string>\r\n  <string>D0 0</string>\r\n  <string>D1 1</string>" +
            "\r\n  <string>D2 2</string>\r\n  <string>D3 3</string>\r\n  <string>D4 4</string>\r\n  <" +
            "string>D5 5</string>\r\n  <string>D6 6</string>\r\n  <string>D7 7</string>\r\n  <strin" +
            "g>D8 8</string>\r\n  <string>D9 9</string>\r\n  <string>Oem1 :</string>\r\n  <string>O" +
            "emPlus ;</string>\r\n  <string>OemComma ,</string>\r\n  <string>OemMinus -</string>\r" +
            "\n  <string>OemPeriod .</string>\r\n  <string>OemQuestion /</string>\r\n  <string>Oem" +
            "3 @</string>\r\n  <string>OemOpenBrackets [</string>\r\n  <string>Oem6 ]</string>\r\n " +
            " <string>OemQuotes ^</string>\r\n  <string>Oem5 \\</string>\r\n  <string>OemBackslash" +
            " ＼</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConvDef {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConvDef"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>513 新規作成...</string>\r\n  <string>514 開く...</string>\r\n  <string>515 保存</stri" +
            "ng>\r\n  <string>516 名前を付けて保存...</string>\r\n  <string>518 web用に保存</string>\r\n  <stri" +
            "ng>520 閉じる</string>\r\n  <string>529 環境設定</string>\r\n  <string>530 次のページ</string>\r\n" +
            "  <string>531 前のページ</string>\r\n  <string>532 ヘルプ→保存</string>\r\n  <string>544 終了</s" +
            "tring>\r\n  <string>769 取り消し</string>\r\n  <string>770 やり直し</string>\r\n  <string>771 " +
            "メモリ開放</string>\r\n  <string>778 塗りつぶし</string>\r\n  <string>785 コピー</string>\r\n  <str" +
            "ing>786 切り取り</string>\r\n  <string>787 貼り付け</string>\r\n  <string>788 消去</string>\r\n " +
            " <string>790 ※1pxごとに上に移動</string>\r\n  <string>791 ※1pxごとに下に移動</string>\r\n  <string" +
            ">792 ※1pxごとに左に移動</string>\r\n  <string>793 ※1pxごとに右に移動</string>\r\n  <string>804 変形 " +
            "拡大縮小回転</string>\r\n  <string>805 貼り付け 透明度付き</string>\r\n  <string>806 コピー 透明度付き</str" +
            "ing>\r\n  <string>1025 キャンバスサイズ</string>\r\n  <string>1026 色調補正 トーンカーブ HSV</string>\r" +
            "\n  <string>1027 色調補正 トーンカーブ HSV</string>\r\n  <string>1028 選択範囲でキャンバスをトリミング</strin" +
            "g>\r\n  <string>1281 新規レイヤー</string>\r\n  <string>1282 レイヤーを複製</string>\r\n  <string>1" +
            "283 レイヤーを削除</string>\r\n  <string>1284 下のレイヤーと結合</string>\r\n  <string>1285 ヘルプ→新規ベク" +
            "タレイヤ（仮置き）</string>\r\n  <string>1287 新規ベクタレイヤ（test）</string>\r\n  <string>1290 レイヤー消" +
            "去</string>\r\n  <string>1296 線画抽出</string>\r\n  <string>1297 レイヤー→左右反転</string>\r\n  <" +
            "string>1298 レイヤー→上下反転</string>\r\n  <string>1299 新規レイヤー(1bit)</string>\r\n  <string>" +
            "1300 新規レイヤー(8bit)</string>\r\n  <string>1302 レイヤー色変更</string>\r\n  <string>1303 フォルダ" +
            "を複製</string>\r\n  <string>1304 フォルダを複製(表示レイヤーのみ)</string>\r\n  <string>1312 下のレイヤーとグ" +
            "ループ化</string>\r\n  <string>1313 グループ解除</string>\r\n  <string>1335 レイヤーを保存</string>\r\n" +
            "  <string>1336 現在のレイヤーのみ表示</string>\r\n  <string>1337 新規グループ</string>\r\n  <string>1" +
            "344 ベクターレイヤー読み込み</string>\r\n  <string>1345 ベクターレイヤー保存</string>\r\n  <string>1360 下の" +
            "レイヤー</string>\r\n  <string>1361 上のレイヤー</string>\r\n  <string>1362 乾燥</string>\r\n  <st" +
            "ring>1392 編集 レイヤーマスク</string>\r\n  <string>1537 すべて選択</string>\r\n  <string>1538 選択解" +
            "除</string>\r\n  <string>1539 選択範囲を反転</string>\r\n  <string>1552 選択範囲を拡張</string>\r\n  " +
            "<string>1553 選択範囲を縮小</string>\r\n  <string>1555 選択範囲表示</string>\r\n  <string>1584 選択" +
            "範囲を拡張1pixel</string>\r\n  <string>1585 選択範囲を縮小1pixel</string>\r\n  <string>2305 サンプル" +
            " 猫ペン4 補正弱</string>\r\n  <string>2306 サンプル 猫ペン4</string>\r\n  <string>2817 新規ビュー</str" +
            "ing>\r\n  <string>2818 左右反転ビュー</string>\r\n  <string>2819 新規タブ</string>\r\n  <string>2" +
            "821 新規タブ2</string>\r\n  <string>2834 ズームイン</string>\r\n  <string>2835 ズームアウト</string" +
            ">\r\n  <string>2836 等倍</string>\r\n  <string>2837 全体表示</string>\r\n  <string>2838 全体表示" +
            " 0°</string>\r\n  <string>2839 回転リセット</string>\r\n  <string>2840 カーソルを中心にズームイン</stri" +
            "ng>\r\n  <string>2841 カーソルを中心にズームアウト</string>\r\n  <string>2848 左右反転</string>\r\n  <st" +
            "ring>2849 上下反転</string>\r\n  <string>2850 キャンバス アンチエイリアス ON/OFF</string>\r\n  <strin" +
            "g>2851 次のビュー</string>\r\n  <string>2852 定規</string>\r\n  <string>2853 定規 軸変更</string" +
            ">\r\n  <string>2854 キャンバス 高画質 ON/OFF</string>\r\n  <string>2855 キャンバス 高画質2 ON/OFF</s" +
            "tring>\r\n  <string>2856 カーソルを中心に左右反転</string>\r\n  <string>2857 カーソルを中心に上下反転</strin" +
            "g>\r\n  <string>2864 スクロール ←</string>\r\n  <string>2865 スクロール →</string>\r\n  <string>" +
            "2866 スクロール ↑</string>\r\n  <string>2867 スクロール ↓</string>\r\n  <string>2880 回転 CW</st" +
            "ring>\r\n  <string>2881 回転 CCW</string>\r\n  <string>2882 回転 大 CW</string>\r\n  <strin" +
            "g>2883 回転 大 CCW</string>\r\n  <string>2884 カーソルを中心に回転 CW</string>\r\n  <string>2885 " +
            "カーソルを中心に回転 CCW</string>\r\n  <string>2886 カーソルを中心に回転 大 CW</string>\r\n  <string>2887" +
            " カーソルを中心に回転 大 CCW</string>\r\n  <string>2888 カーソルを中心に180°回転</string>\r\n  <string>28" +
            "96 回転対称 中心</string>\r\n  <string>2897 左右対称 軸</string>\r\n  <string>2898 カーソルの位置を回転対称" +
            "の中心に設定</string>\r\n  <string>2899 カーソルの位置を左右対称の軸に設定</string>\r\n  <string>2913 読み込み " +
            "消失点1</string>\r\n  <string>2914 読み込み 消失点2</string>\r\n  <string>2915 読み込み 消失点3</stri" +
            "ng>\r\n  <string>2916 読み込み 消失点4</string>\r\n  <string>2917 読み込み 消失点5</string>\r\n  <st" +
            "ring>2918 読み込み 消失点6</string>\r\n  <string>2929 保存 消失点1</string>\r\n  <string>2930 保存" +
            " 消失点2</string>\r\n  <string>2931 保存 消失点3</string>\r\n  <string>2932 保存 消失点4</string>" +
            "\r\n  <string>2933 保存 消失点5</string>\r\n  <string>2934 保存 消失点6</string>\r\n  <string>30" +
            "73 ブラシツール</string>\r\n  <string>3074 消しゴムツール</string>\r\n  <string>3075 選択ブラシツール</st" +
            "ring>\r\n  <string>3076 選択消しゴムツール</string>\r\n  <string>3088 スポイトツール</string>\r\n  <st" +
            "ring>3104 バケツツール</string>\r\n  <string>3105 自動選択ツール</string>\r\n  <string>3106 投げ縄ツー" +
            "ル</string>\r\n  <string>3107 矩形選択ツール</string>\r\n  <string>3108 グラデーションツール</string>\r" +
            "\n  <string>3120 手のひらツール</string>\r\n  <string>3121 ズームツール</string>\r\n  <string>3122" +
            " 回転ツール</string>\r\n  <string>3136 移動ツール</string>\r\n  <string>3168 コマ割りガイドツール</strin" +
            "g>\r\n  <string>3233 ブラシ フリーハンド</string>\r\n  <string>3234 ブラシ 直線</string>\r\n  <strin" +
            "g>3235 ブラシ 連続直線</string>\r\n  <string>3236 ブラシ 曲線</string>\r\n  <string>3237 ブラシ 楕円<" +
            "/string>\r\n  <string>3238 ブラシ 矩形</string>\r\n  <string>3329 ブラシ表示切り替え</string>\r\n  <" +
            "string>3330 レイヤー表示切り替え</string>\r\n  <string>3331 色表示切り替え</string>\r\n  <string>3332" +
            " ナビゲーター表示切り替え</string>\r\n  <string>3334 ※全ウィンドウの表示非表示(現在のtab)</string>\r\n  <string" +
            ">3335 ブラシセット表示切り替え</string>\r\n  <string>3336 ツールオプション</string>\r\n  <string>3337 ※表" +
            "示ウィンドウと非表示ウィンドウを切替（ドッキングパレット除く）</string>\r\n  <string>3345 custom1表示切り替え</string>\r" +
            "\n  <string>3346 custom2表示切り替え</string>\r\n  <string>3347 custom3表示切り替え</string>\r\n " +
            " <string>3348 custom4表示切り替え</string>\r\n  <string>3354 ベクター筆圧</string>\r\n  <string>" +
            "3355 パネル1</string>\r\n  <string>3356 パネル2</string>\r\n  <string>3360 カスタム作成</string>" +
            "\r\n  <string>3361 key設定表示</string>\r\n  <string>3368 レイヤービュー</string>\r\n  <string>33" +
            "69 レイヤービュー左右反転</string>\r\n  <string>3377 レイアウト保存1</string>\r\n  <string>3378 レイアウト保" +
            "存2</string>\r\n  <string>3379 レイアウト保存3</string>\r\n  <string>3380 レイアウト保存4</string>\r" +
            "\n  <string>3393 レイアウト読み込み1</string>\r\n  <string>3394 レイアウト読み込み2</string>\r\n  <stri" +
            "ng>3395 レイアウト読み込み3</string>\r\n  <string>3396 レイアウト読み込み4</string>\r\n  <string>3424 " +
            "ツールボックス→サイズ</string>\r\n  <string>3425 ツールボックス→色</string>\r\n  <string>3426 ツールボックス→" +
            "方向</string>\r\n  <string>3440 パネル1→色</string>\r\n  <string>3441 パネル1→ブラシ1</string>\r\n" +
            "  <string>3442 パネル1→ブラシ2</string>\r\n  <string>3450 タブ</string>\r\n  <string>3456 スタ" +
            "ート</string>\r\n  <string>3457 レイアウト</string>\r\n  <string>3600 バージョン情報</string>\r\n  <" +
            "string>3602 登録</string>\r\n  <string>4113 ブラシサイズ 拡大</string>\r\n  <string>4114 ブラシサイ" +
            "ズ 縮小</string>\r\n  <string>4115 hsvコントロール切り替え</string>\r\n  <string>4120 スポイト 背景色 スク" +
            "リーン</string>\r\n  <string>4121 スポイト 背景色 アクティブレイヤ</string>\r\n  <string>4129 描画色・背景色切" +
            "り替え</string>\r\n  <string>4130 スポイト スクリーン</string>\r\n  <string>4131 描画色を黒・背景色を白に変更<" +
            "/string>\r\n  <string>4134 ツールボックス幅+1</string>\r\n  <string>4135 ツールボックス幅-1</string>" +
            "\r\n  <string>4136 hsvコントロール反転</string>\r\n  <string>4137 スポイト アクティブレイヤ</string>\r\n  " +
            "<string>4145 ブラシ濃度10%</string>\r\n  <string>4146 ブラシ濃度20%</string>\r\n  <string>4147" +
            " ブラシ濃度30%</string>\r\n  <string>4148 ブラシ濃度40%</string>\r\n  <string>4149 ブラシ濃度50%</s" +
            "tring>\r\n  <string>4150 ブラシ濃度60%</string>\r\n  <string>4151 ブラシ濃度70%</string>\r\n  <s" +
            "tring>4152 ブラシ濃度80%</string>\r\n  <string>4153 ブラシ濃度90%</string>\r\n  <string>4160 ブ" +
            "ラシ濃度100%</string>\r\n  <string>4176 透明色切り替え</string>\r\n  <string>4177 前景色 背景色 リンク</" +
            "string>\r\n  <string>4178 連動 H</string>\r\n  <string>4179 連動 S</string>\r\n  <string>4" +
            "180 連動 V</string>\r\n  <string>4181 マルチタッチ風手のひらツール</string>\r\n  <string>4186 ベクター 自" +
            "動選択解除ON/OFF</string>\r\n  <string>4192 分割切り抜き</string>\r\n  <string>4193 分割なし</strin" +
            "g>\r\n  <string>4194 分割 2x2</string>\r\n  <string>4195 分割 4x4</string>\r\n  <string>41" +
            "96 分割 4x4 B</string>\r\n  <string>4200 着せ替え書き出し</string>\r\n  <string>4208 猫補正　品質を有効" +
            "</string>\r\n  <string>4209 猫補正 品質 低</string>\r\n  <string>4213 猫補正 品質 中</string>\r\n " +
            " <string>4218 猫補正 品質 高</string>\r\n  <string>4225 α→temp dir</string>\r\n  <string>4" +
            "226 線消しゴムを使用する</string>\r\n  <string>4227 ブラシをスタンプ風に利用する</string>\r\n  <string>4229 " +
            "コマ割りガイド削除</string>\r\n  <string>4240 ブラシ設定 保存</string>\r\n  <string>4241 ブラシ設定 読み込み<" +
            "/string>\r\n  <string>4242 ブラシ設定を貼り付け</string>\r\n  <string>4243 ブラシ設定をコピー</string>\r" +
            "\n  <string>4256 ブラシ 筆圧 ジッター</string>\r\n  <string>4257 ブラシ 筆圧 格子</string>\r\n  <stri" +
            "ng>4258 ブラシ 筆圧 補充</string>\r\n  <string>4259 ブラシ 筆圧 間隔</string>\r\n  <string>4272 ブラ" +
            "シ レイヤー透明度 ジッター</string>\r\n  <string>4288 自動保存→なし</string>\r\n  <string>4289 自動保存→5分" +
            "</string>\r\n  <string>4290 自動保存→10分</string>\r\n  <string>4291 自動保存→15分</string>\r\n " +
            " <string>4292 自動保存→20分</string>\r\n  <string>4298 ツール一時切り替え→なし</string>\r\n  <string" +
            ">4299 ツール一時切り替え→300</string>\r\n  <string>4300 ツール一時切り替え→500</string>\r\n  <string>4" +
            "304 補正S→0</string>\r\n  <string>4305 補正S→5</string>\r\n  <string>4306 補正S→10</string" +
            ">\r\n  <string>4307 補正S→15</string>\r\n  <string>4308 補正S→20</string>\r\n  <string>432" +
            "0 SIMDを使用しない</string>\r\n  <string>4324 SSE2を使用する</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AllName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ファイル 513 新規作成...</string>\r\n  <string>ファイル 514 開く...</string>\r\n  <string>ファ" +
            "イル 515 保存</string>\r\n  <string>ファイル 516 名前を付けて保存...</string>\r\n  <string>ファイル 518 " +
            "web用に保存</string>\r\n  <string>ファイル 520 閉じる</string>\r\n  <string>ファイル 529 環境設定</stri" +
            "ng>\r\n  <string>ファイル 530 次のページ</string>\r\n  <string>ファイル 531 前のページ</string>\r\n  <st" +
            "ring>ヘルプ 532 ヘルプ→保存</string>\r\n  <string>ファイル 544 終了</string>\r\n  <string>編集 769 取" +
            "り消し</string>\r\n  <string>編集 770 やり直し</string>\r\n  <string>編集 771 メモリ開放</string>\r\n " +
            " <string>編集 778 塗りつぶし</string>\r\n  <string>編集 785 コピー</string>\r\n  <string>編集 786 " +
            "切り取り</string>\r\n  <string>編集 787 貼り付け</string>\r\n  <string>編集 788 消去</string>\r\n  <" +
            "string>編集 790 ※1pxごとに上に移動</string>\r\n  <string>編集 791 ※1pxごとに下に移動</string>\r\n  <st" +
            "ring>編集 792 ※1pxごとに左に移動</string>\r\n  <string>編集 793 ※1pxごとに右に移動</string>\r\n  <stri" +
            "ng>編集 804 変形 拡大縮小回転</string>\r\n  <string>編集 805 貼り付け 透明度付き</string>\r\n  <string>編集" +
            " 806 コピー 透明度付き</string>\r\n  <string>イメージ 1025 キャンバスサイズ</string>\r\n  <string>イメージ 1" +
            "026 色調補正 トーンカーブ HSV</string>\r\n  <string>イメージ 1027 色調補正 トーンカーブ HSV</string>\r\n  <s" +
            "tring>イメージ 1028 選択範囲でキャンバスをトリミング</string>\r\n  <string>レイヤー 1281 新規レイヤー</string>\r\n" +
            "  <string>レイヤー 1282 レイヤーを複製</string>\r\n  <string>レイヤー 1283 レイヤーを削除</string>\r\n  <s" +
            "tring>レイヤー 1284 下のレイヤーと結合</string>\r\n  <string>ヘルプ 1285 ヘルプ→新規ベクタレイヤ（仮置き）</string" +
            ">\r\n  <string>レイヤー 1287 新規ベクタレイヤ（test）</string>\r\n  <string>レイヤー 1290 レイヤー消去</stri" +
            "ng>\r\n  <string>レイヤー 1296 線画抽出</string>\r\n  <string>レイヤー 1297 レイヤー→左右反転</string>\r\n" +
            "  <string>レイヤー 1298 レイヤー→上下反転</string>\r\n  <string>レイヤー 1299 新規レイヤー(1bit)</string" +
            ">\r\n  <string>レイヤー 1300 新規レイヤー(8bit)</string>\r\n  <string>レイヤー 1302 レイヤー色変更</strin" +
            "g>\r\n  <string>レイヤー 1303 フォルダを複製</string>\r\n  <string>レイヤー 1304 フォルダを複製(表示レイヤーのみ)<" +
            "/string>\r\n  <string>レイヤー 1312 下のレイヤーとグループ化</string>\r\n  <string>レイヤー 1313 グループ解除<" +
            "/string>\r\n  <string>レイヤー 1335 レイヤーを保存</string>\r\n  <string>レイヤー 1336 現在のレイヤーのみ表示<" +
            "/string>\r\n  <string>レイヤー 1337 新規グループ</string>\r\n  <string>レイヤー 1344 ベクターレイヤー読み込み<" +
            "/string>\r\n  <string>レイヤー 1345 ベクターレイヤー保存</string>\r\n  <string>α 1360 下のレイヤー</stri" +
            "ng>\r\n  <string>α 1361 上のレイヤー</string>\r\n  <string>レイヤー 1362 乾燥</string>\r\n  <strin" +
            "g>レイヤー 1392 編集 レイヤーマスク</string>\r\n  <string>選択範囲 1537 すべて選択</string>\r\n  <string>選" +
            "択範囲 1538 選択解除</string>\r\n  <string>選択範囲 1539 選択範囲を反転</string>\r\n  <string>選択範囲 155" +
            "2 選択範囲を拡張</string>\r\n  <string>選択範囲 1553 選択範囲を縮小</string>\r\n  <string>選択範囲 1555 選択" +
            "範囲表示</string>\r\n  <string>選択範囲 1584 選択範囲を拡張1pixel</string>\r\n  <string>選択範囲 1585 選" +
            "択範囲を縮小1pixel</string>\r\n  <string>ブラシ 2305 サンプル 猫ペン4 補正弱</string>\r\n  <string>ブラシ " +
            "2306 サンプル 猫ペン4</string>\r\n  <string>ビュー 2817 新規ビュー</string>\r\n  <string>ビュー 2818 左" +
            "右反転ビュー</string>\r\n  <string>ビュー 2819 新規タブ</string>\r\n  <string>ビュー 2821 新規タブ2</str" +
            "ing>\r\n  <string>ビュー 2834 ズームイン</string>\r\n  <string>ビュー 2835 ズームアウト</string>\r\n  <" +
            "string>ビュー 2836 等倍</string>\r\n  <string>ビュー 2837 全体表示</string>\r\n  <string>ビュー 283" +
            "8 全体表示 0°</string>\r\n  <string>ビュー 2839 回転リセット</string>\r\n  <string>ビュー 2840 カーソルを" +
            "中心にズームイン</string>\r\n  <string>ビュー 2841 カーソルを中心にズームアウト</string>\r\n  <string>ビュー 284" +
            "8 左右反転</string>\r\n  <string>ビュー 2849 上下反転</string>\r\n  <string>ビュー 2850 キャンバス アンチエ" +
            "イリアス ON/OFF</string>\r\n  <string>ビュー 2851 次のビュー</string>\r\n  <string>ビュー 2852 定規</" +
            "string>\r\n  <string>ビュー 2853 定規 軸変更</string>\r\n  <string>ビュー 2854 キャンバス 高画質 ON/OFF" +
            "</string>\r\n  <string>ビュー 2855 キャンバス 高画質2 ON/OFF</string>\r\n  <string>ビュー 2856 カーソ" +
            "ルを中心に左右反転</string>\r\n  <string>ビュー 2857 カーソルを中心に上下反転</string>\r\n  <string>ビュー 2864" +
            " スクロール ←</string>\r\n  <string>ビュー 2865 スクロール →</string>\r\n  <string>ビュー 2866 スクロール" +
            " ↑</string>\r\n  <string>ビュー 2867 スクロール ↓</string>\r\n  <string>ビュー 2880 回転 CW</stri" +
            "ng>\r\n  <string>ビュー 2881 回転 CCW</string>\r\n  <string>ビュー 2882 回転 大 CW</string>\r\n  " +
            "<string>ビュー 2883 回転 大 CCW</string>\r\n  <string>ビュー 2884 カーソルを中心に回転 CW</string>\r\n " +
            " <string>ビュー 2885 カーソルを中心に回転 CCW</string>\r\n  <string>ビュー 2886 カーソルを中心に回転 大 CW</s" +
            "tring>\r\n  <string>ビュー 2887 カーソルを中心に回転 大 CCW</string>\r\n  <string>ビュー 2888 カーソルを中心" +
            "に180°回転</string>\r\n  <string>ビュー 2896 回転対称 中心</string>\r\n  <string>ビュー 2897 左右対称 軸" +
            "</string>\r\n  <string>ビュー 2898 カーソルの位置を回転対称の中心に設定</string>\r\n  <string>ビュー 2899 カー" +
            "ソルの位置を左右対称の軸に設定</string>\r\n  <string>ビュー 2913 読み込み 消失点1</string>\r\n  <string>ビュー 2" +
            "914 読み込み 消失点2</string>\r\n  <string>ビュー 2915 読み込み 消失点3</string>\r\n  <string>ビュー 291" +
            "6 読み込み 消失点4</string>\r\n  <string>ビュー 2917 読み込み 消失点5</string>\r\n  <string>ビュー 2918 " +
            "読み込み 消失点6</string>\r\n  <string>ビュー 2929 保存 消失点1</string>\r\n  <string>ビュー 2930 保存 消" +
            "失点2</string>\r\n  <string>ビュー 2931 保存 消失点3</string>\r\n  <string>ビュー 2932 保存 消失点4</s" +
            "tring>\r\n  <string>ビュー 2933 保存 消失点5</string>\r\n  <string>ビュー 2934 保存 消失点6</string>" +
            "\r\n  <string>ツール 3073 ブラシツール</string>\r\n  <string>ツール 3074 消しゴムツール</string>\r\n  <st" +
            "ring>ツール 3075 選択ブラシツール</string>\r\n  <string>ツール 3076 選択消しゴムツール</string>\r\n  <strin" +
            "g>ツール 3088 スポイトツール</string>\r\n  <string>ツール 3104 バケツツール</string>\r\n  <string>ツール 3" +
            "105 自動選択ツール</string>\r\n  <string>ツール 3106 投げ縄ツール</string>\r\n  <string>ツール 3107 矩形選" +
            "択ツール</string>\r\n  <string>ツール 3108 グラデーションツール</string>\r\n  <string>ツール 3120 手のひらツー" +
            "ル</string>\r\n  <string>ツール 3121 ズームツール</string>\r\n  <string>ツール 3122 回転ツール</string" +
            ">\r\n  <string>ツール 3136 移動ツール</string>\r\n  <string>ツール 3168 コマ割りガイドツール</string>\r\n  " +
            "<string>ツール 3233 ブラシ フリーハンド</string>\r\n  <string>ツール 3234 ブラシ 直線</string>\r\n  <str" +
            "ing>ツール 3235 ブラシ 連続直線</string>\r\n  <string>ツール 3236 ブラシ 曲線</string>\r\n  <string>ツー" +
            "ル 3237 ブラシ 楕円</string>\r\n  <string>ツール 3238 ブラシ 矩形</string>\r\n  <string>ウィンドウ 3329" +
            " ブラシ表示切り替え</string>\r\n  <string>ウィンドウ 3330 レイヤー表示切り替え</string>\r\n  <string>ウィンドウ 3" +
            "331 色表示切り替え</string>\r\n  <string>ウィンドウ 3332 ナビゲーター表示切り替え</string>\r\n  <string>ウィンド" +
            "ウ 3334 ※全ウィンドウの表示非表示(現在のtab)</string>\r\n  <string>ウィンドウ 3335 ブラシセット表示切り替え</string" +
            ">\r\n  <string>ウィンドウ 3336 ツールオプション</string>\r\n  <string>ウィンドウ 3337 ※表示ウィンドウと非表示ウィンド" +
            "ウを切替（ドッキングパレット除く）</string>\r\n  <string>ウィンドウ 3345 custom1表示切り替え</string>\r\n  <stri" +
            "ng>ウィンドウ 3346 custom2表示切り替え</string>\r\n  <string>ウィンドウ 3347 custom3表示切り替え</string" +
            ">\r\n  <string>ウィンドウ 3348 custom4表示切り替え</string>\r\n  <string>ウィンドウ 3354 ベクター筆圧</str" +
            "ing>\r\n  <string>ウィンドウ 3355 パネル1</string>\r\n  <string>ウィンドウ 3356 パネル2</string>\r\n  " +
            "<string>ウィンドウ 3360 カスタム作成</string>\r\n  <string>ウィンドウ 3361 key設定表示</string>\r\n  <st" +
            "ring>ウィンドウ 3368 レイヤービュー</string>\r\n  <string>ウィンドウ 3369 レイヤービュー左右反転</string>\r\n  <" +
            "string>ウィンドウ 3377 レイアウト保存1</string>\r\n  <string>ウィンドウ 3378 レイアウト保存2</string>\r\n  <" +
            "string>ウィンドウ 3379 レイアウト保存3</string>\r\n  <string>ウィンドウ 3380 レイアウト保存4</string>\r\n  <" +
            "string>ウィンドウ 3393 レイアウト読み込み1</string>\r\n  <string>ウィンドウ 3394 レイアウト読み込み2</string>\r" +
            "\n  <string>ウィンドウ 3395 レイアウト読み込み3</string>\r\n  <string>ウィンドウ 3396 レイアウト読み込み4</stri" +
            "ng>\r\n  <string>ウィンドウ 3424 ツールボックス→サイズ</string>\r\n  <string>ウィンドウ 3425 ツールボックス→色</" +
            "string>\r\n  <string>ウィンドウ 3426 ツールボックス→方向</string>\r\n  <string>ウィンドウ 3440 パネル1→色</" +
            "string>\r\n  <string>ウィンドウ 3441 パネル1→ブラシ1</string>\r\n  <string>ウィンドウ 3442 パネル1→ブラシ2" +
            "</string>\r\n  <string>ファイル 3450 タブ</string>\r\n  <string>ファイル 3456 スタート</string>\r\n " +
            " <string>ファイル 3457 レイアウト</string>\r\n  <string>ヘルプ 3600 バージョン情報</string>\r\n  <strin" +
            "g>ヘルプ 3602 登録</string>\r\n  <string>ブラシ 4113 ブラシサイズ 拡大</string>\r\n  <string>ブラシ 411" +
            "4 ブラシサイズ 縮小</string>\r\n  <string>α 4115 hsvコントロール切り替え</string>\r\n  <string>ツール 412" +
            "0 スポイト 背景色 スクリーン</string>\r\n  <string>ツール 4121 スポイト 背景色 アクティブレイヤ</string>\r\n  <str" +
            "ing>ツール 4129 描画色・背景色切り替え</string>\r\n  <string>ツール 4130 スポイト スクリーン</string>\r\n  <st" +
            "ring>ツール 4131 描画色を黒・背景色を白に変更</string>\r\n  <string>α 4134 ツールボックス幅+1</string>\r\n  <" +
            "string>α 4135 ツールボックス幅-1</string>\r\n  <string>α 4136 hsvコントロール反転</string>\r\n  <str" +
            "ing>ツール 4137 スポイト アクティブレイヤ</string>\r\n  <string>ブラシ 4145 ブラシ濃度10%</string>\r\n  <st" +
            "ring>ブラシ 4146 ブラシ濃度20%</string>\r\n  <string>ブラシ 4147 ブラシ濃度30%</string>\r\n  <string" +
            ">ブラシ 4148 ブラシ濃度40%</string>\r\n  <string>ブラシ 4149 ブラシ濃度50%</string>\r\n  <string>ブラシ" +
            " 4150 ブラシ濃度60%</string>\r\n  <string>ブラシ 4151 ブラシ濃度70%</string>\r\n  <string>ブラシ 415" +
            "2 ブラシ濃度80%</string>\r\n  <string>ブラシ 4153 ブラシ濃度90%</string>\r\n  <string>ブラシ 4160 ブラ" +
            "シ濃度100%</string>\r\n  <string>ツール 4176 透明色切り替え</string>\r\n  <string>ツール 4177 前景色 背景" +
            "色 リンク</string>\r\n  <string>α 4178 連動 H</string>\r\n  <string>α 4179 連動 S</string>\r\n" +
            "  <string>α 4180 連動 V</string>\r\n  <string>α 4181 マルチタッチ風手のひらツール</string>\r\n  <str" +
            "ing>ツール 4186 ベクター 自動選択解除ON/OFF</string>\r\n  <string>α 4192 分割切り抜き</string>\r\n  <st" +
            "ring>α 4193 分割なし</string>\r\n  <string>α 4194 分割 2x2</string>\r\n  <string>α 4195 分割" +
            " 4x4</string>\r\n  <string>α 4196 分割 4x4 B</string>\r\n  <string>α 4200 着せ替え書き出し</st" +
            "ring>\r\n  <string>ブラシ 4208 猫補正　品質を有効</string>\r\n  <string>ブラシ 4209 猫補正 品質 低</strin" +
            "g>\r\n  <string>ブラシ 4213 猫補正 品質 中</string>\r\n  <string>ブラシ 4218 猫補正 品質 高</string>\r\n" +
            "  <string>α 4225 α→temp dir</string>\r\n  <string>α 4226 線消しゴムを使用する</string>\r\n  <s" +
            "tring>α 4227 ブラシをスタンプ風に利用する</string>\r\n  <string>α 4229 コマ割りガイド削除</string>\r\n  <st" +
            "ring>ブラシ 4240 ブラシ設定 保存</string>\r\n  <string>ブラシ 4241 ブラシ設定 読み込み</string>\r\n  <stri" +
            "ng>ブラシ 4242 ブラシ設定を貼り付け</string>\r\n  <string>ブラシ 4243 ブラシ設定をコピー</string>\r\n  <strin" +
            "g>ブラシ 4256 ブラシ 筆圧 ジッター</string>\r\n  <string>ブラシ 4257 ブラシ 筆圧 格子</string>\r\n  <strin" +
            "g>ブラシ 4258 ブラシ 筆圧 補充</string>\r\n  <string>ブラシ 4259 ブラシ 筆圧 間隔</string>\r\n  <string>" +
            "ブラシ 4272 ブラシ レイヤー透明度 ジッター</string>\r\n  <string>α 4288 自動保存→なし</string>\r\n  <string" +
            ">α 4289 自動保存→5分</string>\r\n  <string>α 4290 自動保存→10分</string>\r\n  <string>α 4291 自" +
            "動保存→15分</string>\r\n  <string>α 4292 自動保存→20分</string>\r\n  <string>ツール 4298 ツール一時切り" +
            "替え→なし</string>\r\n  <string>ツール 4299 ツール一時切り替え→300</string>\r\n  <string>ツール 4300 ツー" +
            "ル一時切り替え→500</string>\r\n  <string>ブラシ 4304 補正S→0</string>\r\n  <string>ブラシ 4305 補正S→" +
            "5</string>\r\n  <string>ブラシ 4306 補正S→10</string>\r\n  <string>ブラシ 4307 補正S→15</strin" +
            "g>\r\n  <string>ブラシ 4308 補正S→20</string>\r\n  <string>α 4320 SIMDを使用しない</string>\r\n  " +
            "<string>α 4324 SSE2を使用する</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AllKeyDef {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllKeyDef"]));
            }
        }
    }
}
